# -e ansible_python_interpreter=/usr/local/bin/python3
# ---
- hosts: mj999
  tasks:
  - name: Create a data container
    docker_container:
      name: mydata
      image: busybox
      volumes:
        - /data
  - name: Re-create a redis container
    docker_container:
      name: myredis
      image: redis
      command: redis-server --appendonly yes
      state: present
      recreate: yes
      exposed_ports:
      - 6379
      volumes_from:
      - mydata
  - name: Restart a container
    docker_container:
      name: myapplication
      image: someuser/appimage
      state: started
      restart: yes
      links:
      - "myredis:aliasedredis"
      devices:
      - "/dev/sda:/dev/xvda:rwm"
      ports:
      - "8080:9000"
      - "127.0.0.1:8081:9001/udp"
      env:
        SECRET_KEY: "ssssh"
          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
        BOOLEAN_KEY: "yes"