apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aliyun-ssd-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-ssd
  resources:
    requests:
      storage: 20Gi
