---
- hosts: mj999
  remote_user: root
  tasks:
  - name: mkdir testfile
    file: 
      path: /testdir/testfile
      state: directory
    notify: handler group1 

  handlers:
  - name: handler1
    listen: handler group1
    file:
      path: /testdir/hd1
      state: touch
  - name: handler2
    listen: handler group1
    file:
      path: /testdir/hd2
      state: touch
