---
- hosts: mj999
  remote_user: root
  tags: all-tag
  tasks:
  - name: task1
    file:
      path: /testdir/t1
      state: touch
    tags: t1,tag1
    
  - name: task2
    file:
      path: /testdir/t2
      state: touch
    tags: ['t2','tag2']
    
  - name: task3
    file:
      path: /testdir/t3
      state: touch
    tags:
      - t3
      - tag3
