apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-pod
spec:
  containers:
  - name: ceph-busybox
    image: busybox
    command: ["sleep", "36000"]
    volumeMounts:
    - name: ceph-vol1
      mountPath: /usr/share/busybox
      readOnly: false
  volumes:
  - name: ceph-vol1
    persistentVolumeClaim:
      claimName: ceph-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-test-ww
  resources:
    requests:
      storage: 1Gi
